name: "Rebuild Armbian and Kernel"
author: "https://github.com/ophub/amlogic-s9xxx-armbian"
description: "Support Amlogic, Rockchip and Allwinner boxes. Default: Armbian 5.9.y kernel"

inputs:
  # Select build target
  build_target:
    description: "Select build target: armbian / kernel"
    required: false
    default: "armbian"

  # For build armbian -----
  armbian_path:
    description: "Set Armbian file path."
    required: false
    default: "build/output/images/*.img"

  armbian_board:
    description: "Set device Board."
    required: false
    default: "all"

  kernel_repo:
    description: "Set kernel repository."
    required: false
    default: "unifreq/kernel"

  kernel_usage:
    description: "Set the tags of the stable kernel."
    required: false
    default: "5.9"

  armbian_kernel:
    description: "Set kernel version."
    required: false
    default: "5.9.y"

  auto_kernel:
    description: "Auto use the latest kernel."
    required: false
    default: "false"

  armbian_fstype:
    description: "Set armbian rootfs type: ext4 / btrfs"
    required: false
    default: "ext4"

  armbian_size:
    description: "Set armbian rootfs size(Unit: MiB)."
    required: false
    default: ""

  builder_name:
    description: "Set Armbian builder signature."
    required: false
    default: ""

  # For compile kernel -----
  kernel_source:
    description: "Select the kernel source code"
    required: false
    default: "unifreq"

  kernel_version:
    description: "Select kernel version"
    required: false
    default: "5.9.y"

  kernel_auto:
    description: "Auto use the latest kernel"
    required: false
    default: "false"

  kernel_package:
    description: "Select compile package list"
    required: false
    default: "all"

  kernel_sign:
    description: "Set the kernel custom signature"
    required: false
    default: "-custom59"

  kernel_toolchain:
    description: "Select the compilation toolchain"
    required: false
    default: "clang"

  kernel_config:
    description: "Set the path of kernel .config"
    required: false
    default: "false"

  kernel_patch:
    description: "Set the directory for kernel patches"
    required: false
    default: "false"

  auto_patch:
    description: "Set whether to use kernel patches"
    required: false
    default: "false"

  compress_format:
    description: "Set the initrd compression format"
    required: false
    default: "xz"

  delete_source:
    description: "Set whether to delete the kernel source"
    required: false
    default: "false"

  silent_log:
    description: "Set whether to use silent log output"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        echo -e "Current running path: [ ${PWD} ]"
        build_target="${{ inputs.build_target }}"
        [[ -z "${build_target}" ]] && build_target="armbian"

        if [[ "${build_target}" == "armbian" ]]; then
            cd ${{ github.action_path }}
            echo -e "Start rebuilding Armbian with kernel 5.9.y..."

            armbian_file="${{ inputs.armbian_path }}"
            armbian_filename="${armbian_file##*/}"
            armbian_filepath="build/output/images"
            [[ -d "${armbian_filepath}" ]] || mkdir -p ${armbian_filepath}

            if [[ "${armbian_file}" == http* ]]; then
                echo -e "Download file: [ ${armbian_file} ]"
                curl -fsSL "${armbian_file}" -o "${armbian_filepath}/${armbian_filename}"
            else
                if [[ -z "$(ls ${armbian_filepath}/${armbian_filename} 2>/dev/null)" ]]; then
                    echo -e "Copy files: [ ${armbian_file} ]"
                    cp -vf ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
                else
                    echo -e "The [ ${armbian_filepath}/${armbian_filename} ] file already exists, skipping."
                fi
            fi
            sync
            echo -e "About the [ ${armbian_filepath} ] directory: \n$(ls -lh ${armbian_filepath} 2>/dev/null)"

            cd ${armbian_filepath}
            down_file="$(ls -l *.img* 2>/dev/null | grep "^-" | awk '{print $9}' | sort -u | head -n 1)"
            if [[ -n "${down_file}" ]]; then
                echo -e "Selected Armbian file: [ ${down_file} ]"
            else
                echo -e "The Armbian file is invalid."
                exit 1
            fi
            [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
            [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
            [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
            echo -e "Armbian file: \n$(ls -lh *.img 2>/dev/null)"

            image_file="$(ls *.img 2>/dev/null | head -n 1)"
            if [[ "${image_file}" =~ "-trunk_" ]]; then
                echo -e "The armbian file name is correct."
            else
                image_version="$(echo ${image_file} | grep -oE '[2-9][0-9]\.[0-9]{1,2}\.[0-9]{1,2}' | head -n 1)"
                image_kernel="$(echo ${image_file} | grep -oE '[5-9]\.[0-9]{1,2}\.[0-9]{1,3}' | head -n 1)"
                image_save_name="Armbian_${image_version}-trunk_${image_kernel}.img"
                rm -f ${image_save_name}
                mv -f ${image_file} ${image_save_name}
                echo -e "Renamed Armbian file: [ ${image_save_name} ]"
            fi

            cd ${{ github.action_path }}
            echo -e "Start to rebuild armbian..."
            make_command=""
            [[ -n "${{ inputs.armbian_board }}" ]] && make_command="${make_command} -b ${{ inputs.armbian_board }}"
            [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
            [[ -n "${{ inputs.kernel_usage }}" ]] && make_command="${make_command} -u ${{ inputs.kernel_usage }}"
            [[ -n "${{ inputs.armbian_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
            [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
            [[ -n "${{ inputs.armbian_fstype }}" ]] && make_command="${make_command} -t ${{ inputs.armbian_fstype }}"
            [[ -n "${{ inputs.armbian_size }}" ]] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
            [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
            sudo ./rebuild ${make_command}

            cd ${{ github.action_path }}/${armbian_filepath}
            pigz -qf *.img || gzip -qf *.img
            for file in *; do [[ -f "${file}" ]] && sha256sum "${file}" >"${file}.sha" 2>/dev/null; done
            rm -f *.sha.sha 2>/dev/null
            sync && sleep 3

            cd ${{ github.action_path }}
            echo "PACKAGED_OUTPUTPATH=${PWD}/${armbian_filepath}" >> ${GITHUB_ENV}
            echo "PACKAGED_OUTPUTDATE=$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
            echo "PACKAGED_STATUS=success" >> ${GITHUB_ENV}
            echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -lh ${PWD}/${armbian_filepath}/ 2>/dev/null)"

        elif [[ "${build_target}" == "kernel" ]]; then
            cd ${{ github.action_path }}
            echo -e "Start compile kernel 5.9.y..."
            sudo ./recompile -r unifreq -k 5.9.y -a false -t clang -n -custom59 -c xz
        else
            echo -e "Please select a build target: armbian / kernel"
            exit 1
        fi

branding:
  icon: "terminal"
  color: "gray-dark"
